clients/urls.py
from django.urls import path
from .views import *

app_name = 'clients'

urlpatterns = [
    path("", ClientListView.as_view(), name='client_list'),
    path("create", ClientCreateView.as_view(), name='client_create'),
    path("<int:client_id>", client_detail, name='client_detail'),
    path("<int:pk>/update", ClientUpdateView.as_view(), name='client_update'),
    path("<int:client_id>/delete", client_delete, name='client_delete'),
    path('<int:client_id>/visits/create', client_visit_create, name='client_visit_create'),
    path('visits/<int:visit_id>', visit_detail, name='visit_detail'),
    path('visits/<int:visit_id>/update', visit_update, name='visit_update'),
    path('visits', VisitListView.as_view(), name='visit_list'),
    path('visits/create', visit_create, name='visit_create'),
    path("search", ClientSearchView.as_view(), name='client_search'),
]

dr_kaif/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('clients.urls')),
]

clients/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.


class Client(models.Model):
    fullname = models.CharField(max_length=100)
    birthdate = models.DateField()
    email = models.CharField(max_length=150, blank=True, null=True)
    phonenumber = models.CharField(max_length=20, blank=True, null=True)
    note = models.TextField(blank=True, null=True)

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

    def __str__(self):
        return self.fullname


class Visit(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='visits')
    visit_date = models.DateTimeField()
    diagnosis = models.TextField(blank=True, null=True)
    therapy = models.TextField(blank=True, null=True)

clients/forms.py
from django.forms import ModelForm, DateInput, DateTimeInput
from .models import Client, Visit


class ClientForm(ModelForm):
    class Meta:
        model = Client
        fields = '__all__'
        widgets = {
            'birthdate': DateInput(attrs={'type': 'date'}),
        }


class VisitForm(ModelForm):
    class Meta:
        model = Visit
        fields = '__all__'
        widgets = {
            'visit_date': DateTimeInput(attrs={'type': 'datetime-local'}),
        }


class VisitCreateForm(ModelForm):
    class Meta:
        model = Visit
        fields = ['visit_date']
        widgets = {
            'visit_date': DateTimeInput(attrs={'type': 'datetime-local'}),
        }


class VisitDetailForm(ModelForm):
    class Meta:
        model = Visit
        fields = ['visit_date', 'diagnosis', 'therapy']
        widgets = {
            'visit_date': DateTimeInput(attrs={'type': 'datetime-local'}),
        }

clients/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.views.decorators.http import require_POST

from .models import Client, Visit
from .forms import *


class ClientListView(ListView):
    model = Client
    template_name = 'clients/clients_list.html'
    context_object_name = 'clients'


class VisitListView(ListView):
    model = Visit
    template_name = 'clients/visit_list.html'
    context_object_name = 'visits'


class ClientCreateView(CreateView):
    form_class = ClientForm
    template_name = 'clients/client_create.html'
    success_url = reverse_lazy('clients:client_list')


def client_detail(request, client_id):
    client = get_object_or_404(Client,
                               id=client_id)
    visits = client.visits.all().order_by('visit_date')
    form = VisitCreateForm()
    context = {'client': client, 'visits': visits, 'form': form}
    return render(request,
                  'clients/client_detail.html',
                  context=context)


def visit_detail(request, visit_id):
    visit = get_object_or_404(Visit,
                              id=visit_id)
    form = VisitDetailForm(data={'visit_date': visit.visit_date,
                                 'diagnosis': visit.diagnosis,
                                 'therapy': visit.therapy})
    context = {'visit': visit,
               'form': form}
    return render(request,
                  'clients/visit_detail.html',
                  context)


def visit_update(request, visit_id):
    visit = get_object_or_404(Visit,
                              id=visit_id)
    form = VisitDetailForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        visit.visit_date = cd['visit_date']
        visit.diagnosis = cd['diagnosis']
        visit.therapy = cd['therapy']
        visit.save()
    return HttpResponseRedirect(reverse('clients:visit_detail', args=[visit.id]))


class VisitDetailView(View):
    def get(self):
        pass

    def post(self):
        pass


class ClientUpdateView(UpdateView):
    model = Client
    form_class = ClientForm
    template_name = 'clients/client_update.html'
    context_object_name = 'client'

    def get_success_url(self):
        return reverse('clients:client_detail', kwargs={'pk': self.object.id})


def client_delete(self, request, client_id):
    client = get_object_or_404(Client, id=client_id)
    client.delete()
    return HttpResponseRedirect(reverse('clients:clients_list'))


class ClientSearchView(ListView):
    model = Client
    template_name = 'clients/client_search.html'
    context_object_name = 'clients'

    def get_queryset(self):
        return Client.objects.filter(fullname__icontains=self.request.GET.get('name'))

    def get_context_data(self, **kwargs):
        context = super(ClientSearchView, self).get_context_data(**kwargs)
        context['find_name'] = self.request.GET.get('name')
        return context


@require_POST
def client_visit_create(request, client_id):
    client = get_object_or_404(Client, id=client_id)
    visit = None
    form = VisitCreateForm(data=request.POST)
    if form.is_valid():
        visit = form.save(commit=False)
        visit.client = client
        visit.save()
        return HttpResponseRedirect(reverse('clients:client_detail', kwargs={'client_id': client_id}))
    else:
        print(form.errors)
        return HttpResponse(f'{form.errors}\n{type(form.errors)}')


def visit_create(request):
    pass

clients/templates/clients/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Dr Kaif{% endblock %}</title>
</head>
<body>
    <h1><a href="{% url 'clients:client_list' %}">Главная</a></h1>
    <h2><a href="{% url 'clients:visit_list' %}">Все записи</a></h2>
    {% block content%}
        There must be some content
    {% endblock %}
</body>
</html>

clients/templates/clients/client_create.html
{% extends "clients/base.html" %}
{% block content %}
<form action="{% url 'clients:client_create' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="save">
</form>
{% endblock %}

clients/templates/clients/client_detail.html
{% extends "clients/base.html" %}
{% block content %}
<p>{{ client.fullname }}</p>
<p>Дата рождения: {{ client.birthdate }}</p>
<p>Электронная почта: {{ client.email }}</p>
<p>Номер телефона: {{ client.phonenumber }}</p>
<p>Заметка: {{ client.note }}</p>
<p><a href="{% url 'clients:client_update' client.id %}">Изменить</a></p>
<p><a href="{% url 'clients:client_delete' client.id %}">Удалить</a></p>
    <h2>Посещения</h2>
    {% for visit in visits %}
        <p><a href="{% url 'clients:visit_detail' visit.id %}">{{ visit.visit_date }}</a></p>
    {% empty %}
        Нет посещений
    {% endfor %}
    {% include 'clients/client_visit_create.html' %}

{% endblock %}

clients/templates/clients/client_search.html
{% extends "clients/base.html" %}
{% block content %}
<form action="{% url 'clients:client_search' %}" method="get">
    <input name="name" type="text" placeholder="Поиск" value="{{ find_name }}">
    <button type="submit">Поиск</button>
</form>
{% if clients %}
    {% for client in clients %}
        <p><a href="{% url 'clients:client_detail' client.id %}">{{ client.fullname }}</a></p>
    {% endfor %}
{% else %}
    <p>Ничего нет</p>
{% endif %}
{% endblock %}

clients/templates/clients/client_update.html
{% extends "clients/base.html" %}
{% block content %}
<form action="{% url 'clients:client_update' client.id %}" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="save">
</form>
{% endblock %}

clients/templates/clients/client_visit_create.html
<h2>Создать посещение</h2>
<form action="{%  url 'clients:client_visit_create' client.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>

{% for field, errors in form.errors.items %}
    <p>ERRORS:</p>
    <p>{{ field }}</p>
    {% for error in errors %}
        <p>{{ error }}</p>
        {% endfor %}
{% endfor %}

clients/templates/clients/clients_list.html
{% extends "clients/base.html" %}
{% block content %}
<p><a href="{% url 'clients:client_create' %}">Создать клиента</a></p>

<form action="{% url 'clients:client_search' %}" method="get">
    <input type="text" name="name" placeholder="Поиск">
    <button type="submit">Поиск</button>
</form>{% for client in clients %}

<p><a href="{% url 'clients:client_detail' client.id %}">{{ client.fullname }}</a></p>
{% endfor %}
{% endblock %}

clients/templates/clients/visit_detail.html
{% extends "clients/base.html" %}
{% block content %}
<p>Дата приема: {{ visit.visit_date }}</p>
<p>Имя клиента: <a href="{% url 'clients:client_detail' visit.client.id %}">{{ visit.client.fullname }}</a></p>
<form action="{% url 'clients:visit_update' visit.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="save">
</form>
{% endblock %}

clients/templates/clients/visit_list.html
{% extends "clients/base.html" %}
{% block content %}
<p><a href="{% url 'clients:visit_create' %}">Создать посещение</a></p>
{% for visit in visits %}

<p><a href="{% url 'clients:visit_detail' visit.id %}">{{ visit.client.fullname }} {{ visit.visit_date }}</a></p>
{% endfor %}
{% endblock %}